#!/bin/bash

while getopts e:d: flag
do
    case "${flag}" in
        e) ENC=${OPTARG};;
        d) DEC=${OPTARG};;
        *) help
    esac
done

BIN=$(basename $0)
mkdir -p "${PWD}/.backup"

function help {
    printf "Usage: \nEncrypt: $BIN -e <folder name>\nDecrypt: $BIN -d <encrypted file>\n"
}

if [ "$ENC" ] && [  "$DEC" ]  ; then
  help
  exit 1
fi

if [ -z "$ENC" ] && [ -z "$DEC" ] ; then 
  help
  exit 1
fi

RUN=$(date +%s)

if [ "$ENC" ] ; then 
    tar -czf "$ENC".tgz "$ENC"
    echo 'Please specify the passphrase you want to use to encrypt the folder'
    read -rs VPASS
    echo "$VPASS" | sha512sum > /var/tmp/"$RUN"
    cat /var/tmp/"$RUN" | gpg --batch --yes --quiet --output - --passphrase-fd 0 --no-symkey-cache --symmetric "$ENC".tgz | base64 -w 60 > "${ENC}.vault"
    \rm -f /var/tmp/"$RUN" "$ENC".tgz 
    unset VPASS 
    printf "Your folder is now encrypted in $ENC.vault\nPlease remember to delete the original folder.\n"
    cp $ENC.vault .backup/$RUN
    exit 0
fi 

if [ "$DEC" ] ; then 
  cp $DEC .backup/$RUN 
  echo "Please specify the passphrase you used to encrypt ${DEC}"
  read -rs VPASS
  echo "$VPASS" | sha512sum > /var/tmp/"$RUN"
  cat $DEC | base64 -d > $DEC.vault
  cat /var/tmp/"$RUN" | gpg --batch --yes --quiet --decrypt --output $DEC.tgz --passphrase-fd 0 $DEC.vault 
  DEC_OUT=$?
  \rm -f /var/tmp/"$RUN"
  unset VPASS 
  if [ $DEC_OUT -ne 0 ] ; then 
    echo "$BIN was unable to decrypt your data. Please try with a different passphrase."
    exit 1
  fi
  tar -C $PWD -xzf $DEC.tgz 
  \rm $DEC.tgz $DEC.vault
  echo "Your data was decrypted in the current folder."
fi
